name: TP 2 package JAR

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_VERSION: "1.0.0"

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@6.0.0
    - name: Setup Java
      uses: actions/setup-java@v1
    - name: Construire Package
      run: mvn clean package -DskipTests
