name: TP 2 package JAR

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_VERSION: "1.0.0"
  MAVEN_OPTS: "-Dmaven.repo.local=/dependances/lib"

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
    - name: Setup Java
      uses: actions/setup-java@v5.0.0
      with:
        java-version: 17
        distribution: zulu

    - name: Prep cache
      run: "sudo mkdir /dependances && sudo mkdir /dependances/lib && sudo chmod 777 /dependances"

    - name: Cache Dependances
      uses: actions/cache@main
      with:
        path: "/dependances/lib"
        key: "cl√© au pif"
          
    - name: Construire Package
      run: mvn clean package -DskipTests ${MAVEN_OPTS}
